### ISSUE TITLE
Doesn't allow github.ref_name to be used as latest tag

### ISSUE THREAD

**Issue by HRADigital** [Requarks/changelog-action#1]
When using `github.ref_name`, the following error appears:
```
Run Requarks/changelog-action@v1
  with:
    token: ***
    tag: master
    writeToFile: false
Error: Provided tag doesn't match latest tag.
```

**Comment by HRADigital** [comment]
cc @NGPixel .

**Comment by HRADigital** [comment]
Should this generate a _CHANGELOG_ from latest tag (_x_), up to `HEAD` (_`ref_name`_)?

**Comment by NGPixel** [comment]
The intended workflow is to either:

- Create a new tag / release (e.g. `v1.2.0`), which triggers the workflow and will generate the changelog between the tag you just created and the previous one (e.g. `v1.1.0`).
- Trigger a workflow manually, which creates a new draft release (and tag), then generate the changelog from that newly created tag and the previous one.

So it won't work from latest tag to HEAD no, although I guess the action could be modified to allows for this scenario.
