### ISSUE TITLE
Not running correctly when using squash merge

### ISSUE THREAD

**Issue by jsmithdlc** [requarks/changelog-action#11]
Hi, we are currently integrating this action into one of our repos but we are having problems with squash merges (using gitflow). The issue is that when, for instance, we develop a feature and then squash merge into develop then the commit message of this merge is structured as follows:

\* feat: commit message 1
\* bugfix: commit message 2
...

The problem is that when we create a release branch from this point in development, the action doesn't recognize the sub-commits specified in the squash merge commit, therefore not updating the CHANGELOG and version correctly. 

Any idea how to deal with this?

**Comment by NGPixel** [comment]
This is not supported as only the commits themselves are processed, not the body. This would be complex to parse as it can contain anything.

If you need the commits from a branch / PR to be preserved, then use a standard merge commit instead. Squash merges are really not meant to be used like that.

**Comment by h1manshu98** [comment]
Hello @jsmithdlc did you find any solution or alternative for this ?

**Comment by haroon9** [comment]
@jsmithdlc @h1manshu98 have you found any solution or a workaround for it?
