### ISSUE TITLE
Item sort order within  category is backwards

### ISSUE THREAD

**Issue by jeacott1** [requarks/changelog-action#17]
Hi,
 I'm testing this action and so far its mostly working pretty well, but I have noticed that within a release category (Bug Fixes, Build System, etc) each item is listed with the latest version at the bottom of the list. This seems at odds with the norm and with the Release order which has the latest first.

thoughts?

**Comment by NGPixel** [comment]
Could be an option.

The Github API doesn't have a parameter to specify the order directly, but the result list could be reversed before processing..

**Comment by NGPixel** [comment]
Added `reverseOrder` option in v1.7.0
