### ISSUE TITLE
Only the first line of a git message is included in the changelog

### ISSUE THREAD

**Issue by jeacott1** [requarks/changelog-action#19]
if I have a multiline commit message:
eg: 
fix: something A
fix: something else B

only the first line gets included in the changelog. 
I expect all the content to end up in the changelog.

**Comment by NGPixel** [comment]
No, as that wouldn't respect the [Conventional Commits](https://www.conventionalcommits.org/) specification.

A commit should be a single fix / feature.
The message body is to optionally provide additional details / context for that commit.
