### ISSUE TITLE
non-lowercase types get ignored

### ISSUE THREAD

**Issue by ShaneMcC** [requarks/changelog-action#21]
A commit message of `Fix: The thing` gets identified as type "Fix" but then discarded:

```
Using input tag: v1.2.3
Using latest tag: v1.2.3
Using previous tag: v1.2.2
[OK] Commit <hash> of type Fix - The thing
Warning: Nothing to add to changelog because of excluded types.
```

(In my cases, excluded types here is set to: `excludedtypes: ''` to include everything)

Looking at the FAQ on https://www.conventionalcommits.org/en/v1.0.0/ these should not be case-sensitive:

> **Are the types in the commit title uppercase or lowercase?**
> Any casing may be used, but it’s best to be consistent.

**Comment by NGPixel** [comment]
Fixed in v1.7.0
