### ISSUE TITLE
No Pr is showing in changelog 

### ISSUE THREAD

**Issue by d4kverma** [requarks/changelog-action#26]
https://github.com/clouddrove-sandbox/auto-change-log/blob/master/.github/workflows/main.yml 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/89906661/235070753-e83f745f-3467-482d-a5ff-1fab9a3395fa.png">
like showing in you changelog .

**Comment by NGPixel** [comment]
These 2 following conditions must be true for the related issue to appear:
- the commit needs to be from a merged PR (either merged or squashed)
- the source PR needs to be linked to an issue

I don't see any PR or issues in the repo you linked to.
