### ISSUE TITLE
Feature: Exclude commits to certain files

### ISSUE THREAD

**Issue by kroese** [requarks/changelog-action#27]
I regularly edit files like `readme.md` or `build.yml`, but I dont want those changes to end up in the changelog.

From the documentation I saw its possible to exclude certain commit types, but that requires me to always remember to add a type to every  commit.

Would it be possible to just exclude commits to certain filenames (or file extensions). So I can just exclude `readme.md` or `*.md` and dont have to worry about types?

**Comment by NGPixel** [comment]
You need types in commits for them to appear in the changelog... That's the whole point of the conventional commits spec. Commits without types will be ignored.

So you can either not put a type for these commits or use a type like `docs:` which you exclude.
