### ISSUE TITLE
Suggestion: Removal of Older Changelog Entries

### ISSUE THREAD

**Issue by nthState-Chris** [requarks/changelog-action#28]
Hi,

I have a changelog with entries from 0.0.1 to 0.1.5, the entries older than 0.5 are of no interest to me anymore and they can be removed from the changelog.

Would it be possible in this GitHub Action to support a max-range of changelog entries...or would that be better as a separate GitHub action?

The idea would be to cull/trim the bottom of the changelog a certain range/number of entries

Kind Regards

Chris

**Comment by NGPixel** [comment]
That would go against the principles of a changelog IMO. Feel free to write a separate action to achieve this but it won't be included in this one.

If the length of the changelog is an issue, I would suggest using GitHub Releases rather than writing the contents to a file.

**Comment by nthState-Chris** [comment]
ah, thank you, I didn't know that :-)
