### ISSUE TITLE
More commits than expected missing from changelog

### ISSUE THREAD

**Issue by sschuberth** [requarks/changelog-action#34]
I'm currently trying to figure out why for [this project](https://github.com/sschuberth/ort) I get [this release](https://github.com/sschuberth/ort/releases/tag/1.0.2):

![image](https://github.com/requarks/changelog-action/assets/349154/556ec7c0-87d0-40bf-92e2-6167f2cab2e0)

Although i the Git history I have:

```
$ git log --oneline 1.0.2 --not 1.0.1 | grep -vE "(build|docs|other|style)"
8deff4b56 WIP
1c804825d WIP
bcd24bda2 refactor(GitHub): Use the more common `github.token`
da42b9396 test(SpmFunTest): Update expected test results
293ebc435 feat(migrate): Add an option to convert NuGet IDs to the namespace format
dc32462e4 refactor(commands): Move configuration migration to a dedicated command
7d5b27952 refactor(package-curation-providers): Make `toCurationPath()` public
af1cbfc19 deps: update dependency com.github.jmongard.git-semver-plugin to v0.6.4
f6d9972bb deps: update dependency clsx to v2
dc6d4a990 deps: update dependency dev.adamko.dokkatoo:dokkatoo-plugin to v2
10fd8a789 deps: update actions/checkout action to v4
13efe5d48 ci: Exclude a URL link in Markdown from the link check
269e00d61 ci: Update reuse configuration for Docusaurus
b3cf8b807 deps: Update the native-gradle-plugin to version 0.9.27
be7ded29b chore(Gradle): Remove forcing the OkHttp version
924dd15b8 chore(batect): Remove the telemetry setting
1f37f99cd deps: update batect to v0.85.0
42b06ae1e revert(codecov): Go back to action v3 from v4
6cc2f5f8f deps: update graphqlplugin to v6.5.6
```

In understand that the "WIP" commits are missing because `includeInvalidCommits` is `false` by default, but why are the "deps", "ci" and "revert" commits missing as well with the default options as `excludeTypes` defaults to `build,docs,other,style` only?

**Comment by NGPixel** [comment]
`deps` is not a valid prefix. Use `chore(deps)` instead.

`ci` is excluded because `build` is. One is simply an alias. Remove `build` from the excluded types and it's gonna work.

`revert` is not supported right now (not technically part of the spec but is suggested), although it could be added.

**Comment by sschuberth** [comment]
First of all, thanks for the quick response. I have some further questions:

> `deps` is not a valid prefix. Use `chore(deps)` instead.

Not valid according to what? [This](https://www.conventionalcommits.org/en/v1.0.0/#summary) explicitly says "types other than `fix:` and `feat:` are allowed". So I guess you're referring to the *recommendations* of the Angular project?

> `ci` is excluded because `build` is. One is simply an alias.

Where's that alias defined? At least the Angular recommendations explicitly list these separately.

**Comment by NGPixel** [comment]
Other types are allowed in the spec but realistically there's no way to account for all possible prefixes that could be used when generating a changelog. There's a full name and icon associated to each. How is the action supposed to know `deps` should translate to a category named "Dependencies" and the relevant icon?

The aliases are defined [here](https://github.com/requarks/changelog-action/blob/main/index.js#L12-L21). Angular list them separately but most people use them interchangeably. The minor difference doesn't warrant a separate category IMO. Modifying the build workflow usually involves modifying the ci as well.

**Comment by sschuberth** [comment]
> How is the action supposed to know `deps` should translate to a category named "Dependencies" and the relevant icon?

Well, via configuration, I guess...

**Comment by NGPixel** [comment]
This is getting a bit too complicated for what is supposed to be a simple action. There's no simple way to request such a complex input from the user. The other solution would involve a custom config file the action would read. This is getting way overkill.

**Comment by sschuberth** [comment]
> This is getting way overkill.

I see. I guess I'll have to have a look at one of those [overkill-solutions](https://jreleaser.org/guide/latest/reference/release/changelog.html) then. Thanks anyway for your insights!

**Comment by sschuberth** [comment]
> `deps` is not a valid prefix. Use `chore(deps)` instead.

Sorry, follow-up question: With `excludeTypes: ""` and `includeInvalidCommits: true`, shouldn't `deps` commits be included under "Other Changes"? Because it seems to me they aren't.
