### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ImLunaHey** [requarks/changelog-action#37]
This is the github actions workflow I'm using.

https://github.com/xirelta/xirelta/blob/59595cbec9e6df2fd97db4285c2b1eddd6b9236c/.github/workflows/ci.yml#L56C1-L79C29

In all of my releases I'm seeing the commit for the release itself. Is there a way to filter this out?

For example the commit in the chore section of this release I want to hide https://github.com/xirelta/xirelta/releases/tag/v0.0.46

![image](https://github.com/requarks/changelog-action/assets/105922175/9d05538f-e2a4-4638-ac20-2d7e21cda2df)

**Comment by ImLunaHey** [comment]
ignore me, its not this action causing the issue.

**Comment by ImLunaHey** [comment]
Actually maybe this is since this is what's generating the output for the github release. 🤔

**Comment by NGPixel** [comment]
You can either use a prefix that's already excluded (like `ci` or `build`) instead of `chore`, or just avoid using any prefix for your release commit. In both cases, the commit will be excluded from the changelog.

**Comment by ImLunaHey** [comment]
Am I able to use `excludeTypes` with `chore(release)` or would it only work for `chore`?

**Comment by NGPixel** [comment]
No, you can only exclude prefixes, not scopes. Although this could be added as an option.

**Comment by NGPixel** [comment]
I added the `excludeScopes` option in v1.9.0.

**Comment by ImLunaHey** [comment]
@NGPixel that works perfectly, thank you. 🙏
