### ISSUE TITLE
Support `permissions: write-all`

### ISSUE THREAD

**Issue by babaric-dev** [requarks/changelog-action#49]
I want this so I don't need to configure my GitHub token permissions... And I think using `permissions: write-all` is prettier.

**Comment by NGPixel** [comment]
Can you provide more details? I have no idea what you're referring to.

**Comment by babaric-dev** [comment]
This permission can grant the same permissions as supplying a GitHub token. So make token optional?

**Comment by babaric-dev** [comment]
https://github.com/requarks/changelog-action/blob/36db8c7ea8582d966f1998a6089c6938bdc11b70/action.yml#L7

change this line to:
`required: false`

**Comment by babaric-dev** [comment]
@NGPixel Please see my PR (#50). It should work.
