### ISSUE TITLE
Most recent version is actually outdated

### ISSUE THREAD

**Issue by Horschig** [requarks/changelog-action#8]
On https://github.com/marketplace/actions/changelog-from-conventional-commits I see that v1 is supposed to be the "most recent version". Looking at this repo, I see that version 1.3.2 is actually newer. I do not know what or why, but it does feel that the marketplace should show the most recent version as 1.3.2 at this point.

**Comment by NGPixel** [comment]
No, they both point to the same commit (0ea1d18) and are identical. Because of how marketplace releases work, two releases must be created for the v1 and the full version number. As such, one will always be created after the other, although they are the same.
