### ISSUE TITLE
Put newest version at the top

### ISSUE THREAD

**Issue by nightscape** [requarks/changelog-action#9]
Hi @NGPixel,

do you have any plans to allow adding the newest version at the top of the changelog?
For a long-lived project, readers always have to scroll down quite a bit otherwise.

Thanks for creating this!
One manual step less for my OS projects 😄

**Comment by NGPixel** [comment]
Both v1 and v1.3.2 are the same exact release (66a4bf2663a93f4271c97e78ec54859e0b40ff95). Use v1 to always use the latest 1.x version or v1.3.2 to lock it to this specific release.

**Comment by nightscape** [comment]
Hi @NGPixel, I'm not sure if your response was for my question or another one. At least I don't understand it 😉

**Comment by NGPixel** [comment]
I just re-read your question. I thought you were referring to the GitHub action version, not the changelog output.

New versions are already added to the top of the changelog. Do you have an example repo where this is not the case?

**Comment by nightscape** [comment]
Ah, if they already should be at the top, then my existing changelog probably doesn't adhere to the required format.
Here's the changelog where the new version was put at the bottom:
https://github.com/crealytics/spark-excel/blob/main/CHANGELOG.md

**Comment by NGPixel** [comment]
Yeah the format is different and it can't find a second level header.

Simply move the latest changelog bit to the top (except the link reference), below the "Next" header. Then the next time it runs, it will properly detect the previous version header and add it to the top. The rest of the changelog can stay in the existing format, e.g.:

```md
# Next

## [v0.18.0] - 2022-08-29 ### :wrench: Chores - [`64521bb`](https://github.com/crealytics/spark-excel/commit/64521bb6f4a9c763d9ed7d4ff8689dfc7c44bbf8) - Update base version *(commit by [@nightscape](https://github.com/nightscape))*

0.17.0
======
- Feature: Add PlainNumberFormat that does not round or use scientific notations for long numbers.
...
```

**Comment by nightscape** [comment]
Ok, cool! Thanks for your quick support 👍 👍
